CREATE TABLE `bama_configuration` (
	`CONFIG_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`CONFIG_NAME` VARCHAR(150) NOT NULL,
	`CONFIG_SLUG` VARCHAR(150) NOT NULL,
	`CONFIG_VALUE` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`CONFIG_ID`)
)
COMMENT='Application Global Configuration'
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT;
